### PR TITLE
Adapt code to work with newer libraries.

### PR DESCRIPTION
**Pull request by yeyeto2788**

### CODE REVIEW

**Comment by not7cd** [comment]
Hi, could you write more about this change? As for formatting, you can use `black`.

**Comment by yeyeto2788** [comment]
My bad! Sorry for not adding more comments, what I did was to instead of using relative import like
```
from . import api, parser, default_per_page
from .fields import book_detail_fields, book_list
```
declare implicitly the imports statements like 
```
from circulation.api import api, parser, default_per_page
from circulation.api.fields import book_detail_fields, book_list
```

I also translate the `book_tag.html` page into English as in the other pages.

And last but not least, I have updated the `requirements.txt` and `pipfile` to use the newer packages of `Flask` , `flask_uploads` and `Werkzeug `.

Regarding formatting I guess it will also be needed to add DocStrings on most of the code, I'll try to do it  when I get time if that is ok for you.

Regards.

**Comment by not7cd** [comment]
Thanks for contribution. This is very strange project that I guess should be archived on my side long time ago. But I'm happy that you choose my fork. I will merge this, but I won't maintain this project or give any road maps regarding it.

**Comment by yeyeto2788** [comment]
Gotcha! thanks anyways. I'll try to make some changes on my repo then to also host ebooks on the app.

Regards.

**Pull request merged**
